### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by dariocravero** [UXtemple/panels#8]
[We're currently fixing our webfont](https://github.com/UXtemple/panels/blob/master/server/render.es6#L3).
Every app has the right to its own :)

**Comment by dariocravero** [comment]
Available through custom css.

Add `public/your-app.com.css` to your project and define your `font-face` or `import` it if you're using google's fonts or some external stylesheet that needs to be linked.

E.g., with your `font-face`:

```css
@font-face {
  font-family: 'Gidole';
  src: url('/gidole.woff') format('woff'), url('/gidole.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

With `import`:

```css
@import url(https://fonts.googleapis.com/css?family=Oswald:300);
```
